language: smalltalk
sudo: false
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
smalltalk:
#  - Pharo-5.0
  - Pharo-4.0
#  - Pharo-3.0
#  - Squeak-4.5
#  - Squeak-5.0
#  - GemStone-3.1.0.6
#  - GemStone-3.2.12
#  - GemStone-3.3.0
#cache:
#  directories:
#    - $SMALLTALK_CI_CACHE
